version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - externa
      - interna
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - externa

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - interna 
    environment:
      PORT: 4000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: my_database

  db:
    image: postgres:15.8
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_database
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - interna

networks:
  externa:
    driver: bridge
  interna:
    driver: bridge

volumes:
  db_data:
